### ISSUE TITLE
Design Docs

### ISSUE THREAD

**Issue by david-dickinson** [Saaaaaage/pictur#1]
## MVP List
- [x] looks excellent

## Schema
- [x] if `posts.status` refers to the post's anonymity, make it a boolean rather than a string
- [x] refactor posts and uploads: ActiveStorage gives us the ability to attach many files to one post, so only the post table is necessary (with automatically generated active_storage_attachments); no need for uploads or the joins table

## Sample State
- [x] update to reflect changes to schema (eg, remove uploads)
    - [x] uploading images for later use (instead of use in posts) can be saved for bonus
- [x] replace snake_case with camelCase
- [x] for posts, change `tags` to `tag_ids`, `comments` to `comment_ids`
- [x] if you want to keep track of views, you’ll need separate table in DB: save that for a bonus feature
- [x] you can give posts only the current user’s vote if you want to protect the anonymity of the other users, or array of `liker_ids` if you don’t care
- [x] for comments, `child_ids` should be `[]` instead of `null`

## Backend Routes
- [x] no backend routes needed for `uploads` - ActiveStorage method calls take care of this

## Frontend Routes
- [x] looks excellent

**Comment by kkossally** [comment]
You can check these off and close this issue now!
