### ISSUE TITLE
User Auth Review

### ISSUE THREAD

**Issue by kkossally** [Saaaaaage/pictur#2]
### Functionality
- [x] demo login works
- [x] able to signup, login, and logout
- [x] displays errors upon invalid input

### Styling
- [x] error messages should be the same style for login and sign up
- [x] error messages should appear/disappear independently for each input
- [x] error messages should not persist when navigating away from and back to the form
- [x] remove error messages that appear in white text above the form

Overall, it looks very good! Nice job with the resizing of the window, though you might want to take another look at how the signup and new post buttons respond to especially narrow windows. Also, you could make some minor changes to the header/navbar area to more closely mirror the original site, especially the searchbar.

**Comment by Saaaaaage** [comment]
Imgur has different styling for the login and the signup pages.  Should I ignore this and unify styles?
