### ISSUE TITLE
Image Upload / Posting

### ISSUE THREAD

**Issue by Saaaaaage** [Saaaaaage/pictur#3]
- [x] Users can upload images to create posts
- [x] Images can be uploaded one or more at a time
- [x] Images can be selected from a browser dialogue or dragged in
- [x] Images are instantly committed to the DB
- [x] Logged in users can edit their own posts
- [x] Posts can be public or hidden
- [x] Public posts can be viewed on the front page
- [x] Hidden posts must be browsed to directly in the URL bar
- [x] Posts can be edited and republished
- [x] Post titles are live-saved

**Comment by kkossally** [comment]
- I was not able to delete my posts when logged in as the demo user
